#!/usr/bin/env bash
#
# Khanshoof full-stack (re)deployment.
#
# Verifies every prerequisite, repairs what it safely can, then rebuilds and
# relaunches the whole stack and proves it actually came up. Designed to be the
# one command needed to stand the service up on a new machine.
#
#   scripts/redeploy.sh              # check, build, deploy, verify
#   scripts/redeploy.sh --check-only # preflight only, change nothing
#   scripts/redeploy.sh --no-build   # restart without rebuilding images
#   scripts/redeploy.sh --yes        # skip the confirmation prompt
#   scripts/redeploy.sh --no-tunnel  # never ask about Cloudflare Tunnel
#
# Safe to re-run. Never touches the Postgres volume or uploads/.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

CHECK_ONLY=0; NO_BUILD=0; ASSUME_YES=0; NO_TUNNEL=0
for arg in "$@"; do
  case "$arg" in
    --check-only) CHECK_ONLY=1 ;;
    --no-build)   NO_BUILD=1 ;;
    --yes|-y)     ASSUME_YES=1 ;;
    --no-tunnel)  NO_TUNNEL=1 ;;
    --help|-h)    sed -n '2,15p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $arg (try --help)" >&2; exit 2 ;;
  esac
done

RED=$'\033[31m'; GRN=$'\033[32m'; YEL=$'\033[33m'; DIM=$'\033[2m'; RST=$'\033[0m'
ok()   { printf "  ${GRN}ok${RST}    %s\n" "$*"; }
warn() { printf "  ${YEL}warn${RST}  %s\n" "$*"; }
fail() { printf "  ${RED}FAIL${RST}  %s\n" "$*"; FAILED=1; }
step() { printf "\n${DIM}==>${RST} %s\n" "$*"; }
die()  { printf "\n${RED}aborted:${RST} %s\n" "$*" >&2; exit 1; }
FAILED=0

# ── 1. Tooling ────────────────────────────────────────────────────────
step "Checking prerequisites"

command -v docker >/dev/null 2>&1 && ok "docker $(docker --version | awk '{print $3}' | tr -d ,)" \
  || fail "docker not installed — see https://docs.docker.com/engine/install/"

if docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"; ok "compose plugin $(docker compose version --short 2>/dev/null)"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"; ok "docker-compose $(docker-compose version --short 2>/dev/null)"
else
  COMPOSE=""; fail "neither 'docker compose' nor 'docker-compose' found"
fi

if docker info >/dev/null 2>&1; then
  ok "docker daemon reachable"
else
  fail "cannot talk to the docker daemon (not running, or user lacks permission —
        try: sudo usermod -aG docker \$USER, then log out and back in)"
fi

command -v git >/dev/null 2>&1 && ok "git $(git --version | awk '{print $3}')" \
  || warn "git missing — player cache version will fall back to a timestamp"

command -v curl >/dev/null 2>&1 && ok "curl present" || fail "curl required for health verification"

avail_kb=$(df -Pk . | awk 'NR==2 {print $4}')
if [ "$avail_kb" -lt 2097152 ]; then
  warn "only $((avail_kb/1024))MB free here — images and Postgres need ~2GB"
else
  ok "disk space $((avail_kb/1024/1024))GB free"
fi

[ -f docker-compose.yml ] || fail "docker-compose.yml not found — run this from the repo"

[ "$FAILED" -eq 0 ] || die "prerequisites missing (see FAIL lines above)"

# ── 2. Configuration ──────────────────────────────────────────────────
step "Checking configuration (.env)"

rand() { LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c "${1:-32}"; }

if [ ! -f .env ]; then
  warn ".env missing — generating one with fresh secrets"
  host_ip=$(hostname -I 2>/dev/null | awk '{print $1}'); host_ip="${host_ip:-localhost}"
  cat > .env <<EOF
# Generated by scripts/redeploy.sh — review the URLs before going public.

# --- secrets (generated; changing them invalidates sessions//data) ---
POSTGRES_PASSWORD=$(rand 32)
SECRET_KEY=$(rand 48)
RENDERER_TOKEN=$(rand 32)
ADMIN_USERNAME=admin
# Must be >= 12 characters or the backend refuses to start.
ADMIN_PASSWORD=$(rand 20)

# --- where this deployment lives (EDIT THESE for a real host) ---
API_BASE_URL=http://${host_ip}:8000
APP_URL=http://${host_ip}:3000
PLAYER_BASE_URL=http://${host_ip}:3001
LANDING_URL=http://${host_ip}:3003
RENDERER_URL=http://renderer:8080
ALLOWED_ORIGINS=http://${host_ip}:3000,http://${host_ip}:3001,http://${host_ip}:3003

# --- runtime ---
DATABASE_URL=postgresql://sawwii:CHANGEME@postgres:5432/sawwii
UPLOAD_DIR=/app/uploads
SESSION_TTL_SECONDS=86400
PREVIEW_TTL_SECONDS=300
MAX_UPLOAD_MB=50
WALLS_PHASE2_ENABLED=true
EOF
  # keep DATABASE_URL's password in step with POSTGRES_PASSWORD
  pw=$(grep '^POSTGRES_PASSWORD=' .env | cut -d= -f2-)
  sed -i "s|^DATABASE_URL=.*|DATABASE_URL=postgresql://sawwii:${pw}@postgres:5432/sawwii|" .env
  ok "created .env — ${YEL}edit the URLs before exposing this publicly${RST}"
  ok "admin password: $(grep '^ADMIN_PASSWORD=' .env | cut -d= -f2-)"
else
  ok ".env present"
fi

envget() { grep -E "^$1=" .env 2>/dev/null | head -1 | cut -d= -f2- || true; }
# Resolved published port for a service: whatever .env says, else the default
# baked into docker-compose.yml. Used by the verification probes and the final
# summary so they follow a port that conflict resolution moved.
portof() { local v; v="$(envget "$1")"; printf '%s' "${v:-$2}"; }

envset() {
  if grep -qE "^$1=" .env; then
    sed -i "s|^$1=.*|$1=$2|" .env
  else
    printf '%s=%s\n' "$1" "$2" >> .env
  fi
}

# Anything absent or empty here means the stack will not come up correctly.
for key in POSTGRES_PASSWORD SECRET_KEY ADMIN_USERNAME ADMIN_PASSWORD \
           DATABASE_URL API_BASE_URL APP_URL PLAYER_BASE_URL RENDERER_TOKEN; do
  if [ -z "$(envget "$key")" ]; then fail "$key is missing or empty in .env"; else ok "$key set"; fi
done

# ADMIN_PASSWORD is validated by the backend ONLY while bootstrapping an empty
# database, so a short value is harmless on an established deployment and fatal
# on a fresh one. Warn here (the database may not be up yet to tell which case
# this is) and hard-fail later, once we can actually look.
adminpw="$(envget ADMIN_PASSWORD)"
ADMIN_PW_SHORT=0
if [ -n "$adminpw" ] && [ "${#adminpw}" -lt 12 ]; then
  ADMIN_PW_SHORT=1
  warn "ADMIN_PASSWORD is ${#adminpw} chars (minimum 12). Harmless for an existing
        database, but a FRESH deployment would crash while seeding the first admin."
else
  ok "ADMIN_PASSWORD length acceptable"
fi

# DATABASE_URL must carry the same password compose gives Postgres, or every
# query fails auth against a database that itself started fine.
dburl="$(envget DATABASE_URL)"; pgpw="$(envget POSTGRES_PASSWORD)"
case "$dburl" in
  *sqlite*) fail "DATABASE_URL points at sqlite; this stack requires Postgres" ;;
  *":${pgpw}@"*) ok "DATABASE_URL password matches POSTGRES_PASSWORD" ;;
  *) fail "DATABASE_URL password does not match POSTGRES_PASSWORD — auth will fail" ;;
esac

[ "$FAILED" -eq 0 ] || die "configuration problems above must be fixed first"

# ── 3. Host-specific values ───────────────────────────────────────────
step "Deriving host-specific settings"

if [ -z "${PLAYER_VERSION:-}" ]; then
  if git rev-parse --short HEAD >/dev/null 2>&1; then
    PLAYER_VERSION="$(git rev-parse --short HEAD)"
  else
    PLAYER_VERSION="t$(date +%s)"
  fi
fi
# Written into .env, not just exported: compose reads .env for build-arg
# interpolation, so an exported-only value can silently build the old stamp
# and leave every TV serving a cached player.
envset PLAYER_VERSION "$PLAYER_VERSION"
ok "PLAYER_VERSION=$PLAYER_VERSION (busts the player service-worker cache)"

mkdir -p data uploads && ok "data/ and uploads/ present"

# ── 4. Ports ──────────────────────────────────────────────────────────
step "Checking published ports"

# Ports are overridable (compose reads ${API_PORT} etc. with these defaults),
# so a conflict is something we can resolve rather than only report.
port_listening() {
  if command -v ss >/dev/null 2>&1; then ss -ltn 2>/dev/null | grep -qE "[:.]$1[[:space:]]"
  elif command -v netstat >/dev/null 2>&1; then netstat -ltn 2>/dev/null | grep -qE "[:.]$1[[:space:]]"
  else
    # No socket tools: fall back to asking whether anything answers there.
    ! curl -s -o /dev/null --max-time 1 --connect-timeout 1 "http://127.0.0.1:$1/" 2>/dev/null && return 1 || return 0
  fi
}

# Which container, if any, publishes this port. Works without root, unlike
# reading process names out of ss.
port_container() {
  docker ps --format '{{.Names}}\t{{.Ports}}' 2>/dev/null \
    | awk -F'\t' -v p=":$1->" '$2 ~ p {print $1; exit}'
}

ours_container() { case "$1" in signage_*|"${COMPOSE_PROJECT_NAME:-}"_*) return 0 ;; *) return 1 ;; esac; }

# First free port at or above $1 that nothing holds and we have not already
# handed to another service in this same run.
suggest_port() {
  local cand="$1" limit=$(( $1 + 200 ))
  while [ "$cand" -le "$limit" ]; do
    case " $ASSIGNED " in *" $cand "*) cand=$((cand+1)); continue ;; esac
    if ! port_listening "$cand"; then printf '%s' "$cand"; return 0; fi
    cand=$((cand+1))
  done
  return 1
}

ASSIGNED=""
PORTS_CHANGED=0
# service:env-var:default
for entry in "API:API_PORT:8000" "Dashboard:APP_PORT:3000" "Player:PLAYER_PORT:3001" "Landing:LANDING_PORT:3003"; do
  label="${entry%%:*}"; rest="${entry#*:}"; var="${rest%%:*}"; default="${rest##*:}"
  want="$(envget "$var")"; want="${want:-$default}"

  if ! port_listening "$want"; then
    ok "$label port $want free"
    ASSIGNED="$ASSIGNED $want"
    continue
  fi

  holder="$(port_container "$want")"
  if [ -n "$holder" ] && ours_container "$holder"; then
    ok "$label port $want held by this stack ($holder) — will be replaced"
    ASSIGNED="$ASSIGNED $want"
    continue
  fi

  # A genuine conflict: something else owns the port.
  if [ -n "$holder" ]; then
    who="container '$holder'"
  else
    who="$(command -v ss >/dev/null 2>&1 && ss -ltnp 2>/dev/null | grep -E "[:.]$want[[:space:]]" \
           | grep -oE 'users:\(\("[^"]+' | head -1 | sed 's/.*"//')"
    who="${who:+process '$who'}"; who="${who:-another process}"
  fi

  alt="$(suggest_port $((want + 10)) || true)"
  if [ -z "$alt" ]; then
    fail "$label port $want is taken by $who and no free port found nearby"
    continue
  fi

  if [ -t 0 ] && [ "$ASSUME_YES" -eq 0 ]; then
    printf "  ${YEL}conflict${RST}  %s port %s is taken by %s\n" "$label" "$want" "$who"
    printf "            use %s instead? [Y/n] " "$alt"
    read -r ans </dev/tty || ans=""
    case "$ans" in
      [nN]*) fail "$label port $want unavailable and no alternative accepted" ;;
      *) envset "$var" "$alt"; ASSIGNED="$ASSIGNED $alt"; PORTS_CHANGED=1
         ok "$label moved to port $alt (saved as $var in .env)" ;;
    esac
  else
    fail "$label port $want is taken by $who. Free it, or set $var=$alt in .env
        (suggested: $alt is free). Re-run with a terminal attached to be offered this."
  fi
done

[ "$FAILED" -eq 0 ] || die "port conflicts must be resolved before deploying"

if [ "$PORTS_CHANGED" -eq 1 ]; then
  warn "Published ports changed. If a Cloudflare Tunnel fronts this host, update its
        Public Hostname routes to the new local ports, or the public URLs will 502."
fi

if [ "$CHECK_ONLY" -eq 1 ]; then
  printf "\n${GRN}Preflight passed.${RST} Re-run without --check-only to deploy.\n"; exit 0
fi

# ── 5. Deploy ─────────────────────────────────────────────────────────
if [ "$ASSUME_YES" -eq 0 ]; then
  printf "\nAbout to rebuild and restart the whole stack in %s\n" "$ROOT_DIR"
  printf "Data in data/ and uploads/ is preserved. Continue? [y/N] "
  read -r reply </dev/tty || reply=""
  case "$reply" in [yY]*) ;; *) die "cancelled by user" ;; esac
fi

step "Starting datastores"
$COMPOSE up -d postgres redis
ok "postgres + redis requested"

# The backend trusts proxy headers only from this address. The Docker bridge
# gateway differs per host, so it is read from the live network rather than
# assumed -- this is the setting most likely to be wrong after a move.
net="$($COMPOSE ps -q postgres 2>/dev/null | head -1 | xargs -r docker inspect \
       -f '{{range $k,$v := .NetworkSettings.Networks}}{{$k}}{{end}}' 2>/dev/null || true)"
gw="$(docker network inspect "${net:-bridge}" -f '{{range .IPAM.Config}}{{.Gateway}}{{end}}' 2>/dev/null || true)"
if [ -n "$gw" ]; then
  envset FORWARDED_ALLOW_IPS "$gw"
  ok "FORWARDED_ALLOW_IPS=$gw (docker gateway on this host)"
else
  warn "could not determine the docker gateway; leaving FORWARDED_ALLOW_IPS as-is"
fi

# Now that Postgres is reachable, settle the ADMIN_PASSWORD question: only a
# database with no users will run the bootstrap that rejects a short password.
if [ "$ADMIN_PW_SHORT" -eq 1 ]; then
  users="$($COMPOSE exec -T postgres psql -U sawwii -d sawwii -tAc \
           "SELECT count(*) FROM users" 2>/dev/null | tr -d '[:space:]' || echo "")"
  if [ -z "$users" ] || [ "$users" = "0" ]; then
    fail "ADMIN_PASSWORD is too short and this database has no users yet, so the
          backend will crash seeding the first admin. Set a password of at least
          12 characters in .env and re-run."
    die "refusing to deploy into a guaranteed crash loop"
  else
    ok "short ADMIN_PASSWORD is inert here ($users existing users; bootstrap will not run)"
  fi
fi

step "Building and starting the stack"
if [ "$NO_BUILD" -eq 1 ]; then $COMPOSE up -d; else $COMPOSE up -d --build; fi

# ── 6. Wait for health ────────────────────────────────────────────────
step "Waiting for services to report healthy"
deadline=$(( $(date +%s) + 180 ))
while :; do
  unhealthy=""
  for svc in postgres redis backend frontend player landing renderer; do
    cid="$($COMPOSE ps -q "$svc" 2>/dev/null | head -1)"
    [ -n "$cid" ] || { unhealthy="$unhealthy $svc(missing)"; continue; }
    state="$(docker inspect -f '{{.State.Status}}' "$cid" 2>/dev/null || echo unknown)"
    health="$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "$cid" 2>/dev/null || echo none)"
    [ "$state" = "running" ] || { unhealthy="$unhealthy $svc($state)"; continue; }
    case "$health" in healthy|none) ;; *) unhealthy="$unhealthy $svc($health)" ;; esac
  done
  [ -z "$unhealthy" ] && { ok "all services healthy"; break; }
  if [ "$(date +%s)" -ge "$deadline" ]; then
    fail "timed out waiting for:$unhealthy"
    printf "\n%s\n" "$($COMPOSE ps)"
    die "services did not become healthy — inspect with: $COMPOSE logs --tail 50"
  fi
  sleep 5
done

# ── 7. Verify ─────────────────────────────────────────────────────────
step "Verifying the deployment"

probe() {  # name url expected
  code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 "$2" 2>/dev/null || echo 000)"
  if [ "$code" = "$3" ]; then ok "$1 -> $code"; else fail "$1 -> $code (expected $3)"; fi
}
P_API="$(portof API_PORT 8000)";     P_APP="$(portof APP_PORT 3000)"
P_PLAY="$(portof PLAYER_PORT 3001)"; P_LAND="$(portof LANDING_PORT 3003)"
probe "API    (localhost:$P_API/plans)" "http://localhost:$P_API/plans" 200
probe "App    (localhost:$P_APP)"       "http://localhost:$P_APP/"      200
probe "Player (localhost:$P_PLAY)"      "http://localhost:$P_PLAY/"     200
probe "Landing(localhost:$P_LAND)"      "http://localhost:$P_LAND/"     200

if $COMPOSE exec -T redis redis-cli ping 2>/dev/null | grep -q PONG; then
  ok "redis responding"
else
  fail "redis not responding — rate limits will fall back to per-process counters"
fi

if $COMPOSE exec -T postgres psql -U sawwii -d sawwii -tAc \
     "SELECT 1 FROM information_schema.tables WHERE table_name='organizations'" 2>/dev/null | grep -q 1; then
  ok "database schema present"
else
  fail "schema missing — check: $COMPOSE logs backend"
fi

workers="$($COMPOSE ps -q backend | head -1 | xargs -r docker top 2>/dev/null | grep -c 'multiprocessing-fork' || echo 0)"
[ "$workers" -gt 0 ] && ok "backend running $workers workers" || warn "could not count backend workers"

served="$(curl -s --max-time 10 "http://localhost:$P_PLAY/sw.js" 2>/dev/null | head -1)"
case "$served" in
  *"$PLAYER_VERSION"*) ok "player cache stamped $PLAYER_VERSION" ;;
  *) warn "player sw.js does not carry $PLAYER_VERSION — TVs may serve a cached build" ;;
esac

# ── 8. Report ─────────────────────────────────────────────────────────
if [ "$FAILED" -ne 0 ]; then
  printf "\n${RED}Deployment finished with problems.${RST} See FAIL lines above.\n"
  printf "Logs: %s logs --tail 50\n" "$COMPOSE"
  exit 1
fi

# ── Cloudflare Tunnel (optional) ──────────────────────────────────────
# The tunnel is what publishes this stack on its public hostnames, and it runs
# on the host rather than in the compose stack -- so it is the one piece a move
# to a new machine does not carry over. Only raise it when it is actually
# missing, and only when there is a human present to answer.
if [ "$NO_TUNNEL" -eq 0 ] && ! command -v cloudflared >/dev/null 2>&1; then
  if [ -t 0 ] && [ "$ASSUME_YES" -eq 0 ]; then
    step "Public access"
    printf "  Reachable locally. No cloudflared on this host -- fine if your\n"
    printf "  tunnel runs on another machine, otherwise nothing publishes this.\n"
    printf "  Install Cloudflare Tunnel as a service now? [y/N] "
    read -r want </dev/tty || want=""
    case "$want" in
      [yY]*) "$ROOT_DIR/scripts/setup-tunnel.sh" || warn "tunnel setup did not complete — rerun scripts/setup-tunnel.sh" ;;
      *)     ok "skipped — run scripts/setup-tunnel.sh whenever you want it" ;;
    esac
  else
    warn "no cloudflared on this host. If your tunnel runs elsewhere that is
        expected; otherwise run scripts/setup-tunnel.sh to publish this stack."
  fi
fi

printf "\n${GRN}Stack is up.${RST}\n\n"
printf "  Dashboard  %s\n" "$(envget APP_URL)"
printf "  Player     %s\n" "$(envget PLAYER_BASE_URL)"
printf "  API        %s\n" "$(envget API_BASE_URL)"
printf "  Landing    %s\n" "$(envget LANDING_URL)"
printf "\n  ${DIM}local: :%s dashboard  :%s player  :%s api  :%s landing${RST}\n" \
  "$P_APP" "$P_PLAY" "$P_API" "$P_LAND"
printf "  ${DIM}logs:  %s logs -f backend${RST}\n\n" "$COMPOSE"
